> #Pitching Stats Data  
> str(ps)  
> summary(ps)
> ps$`2b `[is.na(ps$`2b `)] <- with(ps, median(ps$`2b `, na.rm = TRUE))
> which((is.na(ps$`2b `)))
> which((is.na(ps$`3b `)))
> ps$`3b `[is.na(ps$`3b `)] <- with(ps, median(ps$`3b `, na.rm = TRUE))
> which((is.na(ps$`3b `)))
> which((is.na(ps$`hr `)))
> ps$`hr `[is.na(ps$`hr `)] <- with(ps, median(ps$`hr `, na.rm = TRUE))
> which((is.na(ps$`hr `)))
> which((is.na(ps$`ab `)))
> ps$`ab `[is.na(ps$`ab `)] <- with(ps, median(ps$`ab `, na.rm = TRUE))
> which((is.na(ps$`ab `)))
> which((is.na(ps$`b/avg `)))
> ps$`b/avg `[is.na(ps$`b/avg `)] <- with(ps, median(ps$`b/avg `, na.rm = TRUE))
> which((is.na(ps$`b/avg `)))
> which((is.na(ps$`wp `)))
> ps$`wp `[is.na(ps$`wp `)] <- with(ps, median(ps$`wp `, na.rm = TRUE))
> which((is.na(ps$`wp `)))
> which((is.na(ps$`hbp `)))
> ps$`hbp `[is.na(ps$`hbp `)] <- with(ps, median(ps$`hbp `, na.rm = TRUE))
> which((is.na(ps$`hbp `)))
> which((is.na(ps$`bk `)))
> ps$`bk `[is.na(ps$`bk `)] <- with(ps, median(ps$`bk `, na.rm = TRUE))
> which((is.na(ps$`bk `)))

#Offensive Stats Data 
> str(os)
> summary(os)                                    
> which((is.na(os$`tb `)))
> os$`tb `[is.na(os$`tb `)] <- with(os, median(os$`tb `, na.rm = TRUE))
> which((is.na(os$`tb `)))
> which((is.na(os$`slg% `)))
> os$`slg% `[is.na(os$`slg% `)] <- with(os, median(os$`slg% `, na.rm = TRUE))
> which((is.na(os$`slg% `)))
> which((is.na(os$`gdp `)))
> os$`gdp `[is.na(os$`gdp `)] <- with(os, median(os$`gdp `, na.rm = TRUE))
> which((is.na(os$`gdp `)))
> which((is.na(os$`ob% `)))
> os$`ob% `[is.na(os$`ob% `)] <- with(os, median(os$`ob% `, na.rm = TRUE))
> which((is.na(os$`ob% `)))
> which((is.na(os$`sf `)))
> os$`sf `[is.na(os$`sf `)] <- with(os, median(os$`sf `, na.rm = TRUE))
> which((is.na(os$`sf `)))
> which((is.na(os$`sh `)))
> os$`sh `[is.na(os$`sh `)] <- with(os, median(os$`sh `, na.rm = TRUE))
> which((is.na(os$`sh `)))
> View(os)
> View(ps)